apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-credentials
  namespace: default
spec:
  encryptedData:
    connection: AgBQI1CQYb84n1A/D8DSSBvkQ+sAqbCTKHJAVR1OQic
iZKc4n/Kcs/sxnuZ9y/20o3HqMVVAtCC/eknuUpV9Zr5FZbLdRvVXTcufjI
uB8jkC9EoGLY72V5NYMTLQCEUuu0kFngDQl52f3OzMxAmgq7IKRYalJnwXy
4huD0fy9rGZGNfI2CeKI5atV1g33lyGU6XV3aTm7HGhRh/zKZWxxdKKGFta
G4HagKJTWyF52s2Z6gBQqwNIfRwrdcENakCMCRsdR7X+Qwj++KIoh71f0UZ
Bhz7j8cSDfZHFhxgmz5SmZSMxw6vEmjlll/aTWjSvjNsFPJ+7qQzuDHk10b
HGbWhzlaew2b3lP8lBxfu0wKHzRWQOnTOsmr8SBIwt3UOkgL6NJrhxKe2Ng
HWMNiiZBczyACZfu9ZmZ32v+QZ9vIdliD/fL8Kp4YPuDB5xX3fcUQOXanb7
fteaGshCh5xqDr4PcVCAFbPtd251AYz1WyCDPn1XdrmXmKuSQB7pcdc6crJ
TJO77aZwvbezLXBJFbj8Clit3S0dD75X7QNLN93ugI1hpb301vqsmUMCEW2
BHO52v/gMeQr71FtKNLSFtXOhjToYJyUzmwPqxLa2nmUIZL1MJ6v0a/aex+
msa63KXA3axo+LftK11MQVuYRfRTXPsSRunconvrgmp/xQ/WORGBW95V3Hi
lAJXDSpTGiGvE4aM2JDYNj80H427QAz/tR9h6flod9gtiWDr1hznLfRHsZg
=
    password: AgBUF6fBB39MUf2fxEpF543Rd0vInewM1w6wM7lyKcnb+
i1caNchQcfdq32cr0FSKeuVnEHHMXAnTwGIX5nie3H7YQCw6DijifMQIEOz
e/YL60t3n5ah+QtdRuAiE75TP6f8Tn8zMH11GFewSESumrclyDs7GPGwIUy
v2VzLUXZg1kFTRGE5x9elOSoXaB1UmEi66KA5f7fY611WtiwWUu+KKsf+Bk
Kd+FpVXQHnNtBo3RO+EjW6pse3XBck3EGY+DmFgioyv7Q+J4lbdqueVriHz
eHkRiuo3TxbFu4R3E9fgaHv24BaJ0uYOZAEQNd6Nb4y1GExOlTDiFMcv/Iw
P1PDfC/R8bCJ1wBgggvls6/AY16PpS/HXtKW+nnDUnZzSHbIBipFIgU4Clz
cqAZ60QG4GZxdM55y0ZvKZS7FArqzwIIN/I5ZDEUlkUUfZOMVVZcFLY8Prf
H+RtCrq/72c972iIl/0HiQDhDBvyasnPOhfrNotyMYbx3Dwb6fMh0Ezq7Yz
Rz211UPSljJqxQWpngAx5Hii1PTraTBNDSOtracB/ttV/pzN8qHvRyN6zAm
MaeANylBbZo/b92LM89thoHK/l/JqIWMnsl7mGm1P5GU/HQ3gv83Ab/rOhX
Fbg4QYgTh96uE3luD74teue16nhzxx6lSpESH5DZW8t095e4rAQ/nfLV9AK
zg7SQeUm/sB7cndmNLxBN83yvOkpv4zyY=
    username: AgCylKEj7MFoEbz6r3pAYlSZRYGm5uEGZWFemO5tom8u/
ZM2Tik5fmAjlwswUB0Jv6J9gQqN6eoyb74kQoxX4qDudLKmfYxezQDnDaQi
hOlrXLdUjYiSzOBMWXmhmGW6x6/Flh11bxfFefpcQQiXhwtA4yPlr65BHit
kmsgs/A8PArRTJ8DxHDA7wGfzElALWxWvD9oHy3tED8mjqHhpTFfH3p3jBx
RwmIqcK6hKX440/8xQN6oiEUltFwbBn8lefFXHxckwANESjYZpiNfRuXHXe
hE4tVomc8PIHmJwEa0GG7VOrXvykYNgBSOXlPHBeJiB41CpzvyB1jK4Ai3a
Niyc4aGrSe6ySXEuALoy6iQRTEZft4Ri8lpxwyo6448+uh4K3iU2sqQSQUc
Gm0KWkqoX6185PCN2B94N1vvyeNCcfazEgiZFIcLhCFoTg/ffLNN8SFQuFw
rrp01ryrAvvxe6wij0dYWBLj6fOrPfQ+0jxpj4V7n1FZetoQ8mEdXUmJ+Li
qdcsv88d5aP9w+vyvv8skiO5wVEyQE1AclsCUn31fduThK6lK6xjTjoH3Ts
/MFQffgWHqrn2mc124zXAayTwmv0QfUMCkEPmWto9QQLpklXLDqfaX0QrLY
Wtq9a8WH9J/DwDBPaiE9NfYtip8saJXJJsgqRBjhtXvg/2zrPzwMCJiVYow
Y4z0d7euWIETFXwMpJx8HBlQCD+g==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysql-credentials
      namespace: default
    type: Opaque
